### ISSUE TITLE
UI: Env detail request failures for certain environments

### ISSUE THREAD

**Issue by mikeykhalil** [dollarshaveclub/acyl#117]
We are noticing 500 error codes coming from the following endpoint of certain environments: 

`req.open('GET', `${apiBaseURL}/v2/userenvs/${envName}`, true);`

This prevents the page from loading properly and doesn't surface an error to the user, apart from the console logs. 

The root issue is that we basically return a 500 if any event log's status is set to "nil" 
```
error getting eventlogs from db: error scanning row: sql: Scan error on column index 10, name "status": unexpected type for value: <nil> (wanted []byte)
```

**Comment by mikeykhalil** [comment]
Found out more about this issue by inspecting the database. 

It does seem like there are certain scenarios where the status of an event log is nil. Not exactly sure how we want to handle this. We could create a default value, or perhaps not return an event log in this specific handler if the event log never obtained a status.

**Comment by bkeroackdsc** [comment]
> After reading more of the code, seems like we should be calling SetNewStatus first

**Comment by mikeykhalil** [comment]
Fixed by https://github.com/dollarshaveclub/acyl/pull/118
