### ISSUE TITLE
Slack notifier can propagate error message as namespace name

### ISSUE THREAD

**Issue by mikeykhalil** [dollarshaveclub/acyl#36]
Template: `K8s Namespace: {{ .K8sNamespace }}

Rendered slack message:
`K8s Namespace: <error getting namespace: error getting k8s env: context canceled>`

**Comment by bkeroackdsc** [comment]
This is intentional behavior: https://github.com/dollarshaveclub/acyl/blob/master/pkg/nitro/env/env.go#L149

We still want to send a notification even if some of the template data can't be retrieved for some reason.

**Comment by mikeykhalil** [comment]
Makes sense, thanks for confirming.
