### ISSUE TITLE
Allow new dependency type - container/docker to reduce unnecessary docker image builds

### ISSUE THREAD

**Issue by cleanshavenalex** [dollarshaveclub/acyl#40]
Allow a new dependency type that allows pre-existing container for a dependency to be used to reduce build times and unnecessary image builds for dependencies that do not change often

**Comment by bkeroackdsc** [comment]
Acyl uses commit SHA image tags, so if the HEAD of the branch of the dependency doesn't change, no new image should be built (assuming the same image repository used).

**Comment by bkeroackdsc** [comment]
Closing as invalid (`chart_path`/`chart_repo_path` could be used in this case).
