### ISSUE TITLE
add a sanity check prior to any kind of namespace operation

### ISSUE THREAD

**Issue by cleanshavenalex** [dollarshaveclub/acyl#41]
given a namespace for a DQA was deleted - could have been manually or by ACYL
when there is an update to the PR associated with the deleted namespace
then ACYL will call metahelm to install charts into that namespace
and will not return an error but will timeout 
leaving DQA stuck in spawning state

"2019/08/15 16:30:04 event: d77c43d3-3ac9-40cb-ae05-1e884fa73b52: metahelm: cloudkeeper: install callback indicated Continue; proceeding\n",
    "2019/08/15 16:30:04 event: d77c43d3-3ac9-40cb-ae05-1e884fa73b52: metahelm: cloudkeeper-proxy: install callback indicated Continue; proceeding\n",
    "2019/08/15 16:30:04 event: d77c43d3-3ac9-40cb-ae05-1e884fa73b52: metahelm: cloudkeeper: running helm install\n",
    "2019/08/15 16:30:04 event: d77c43d3-3ac9-40cb-ae05-1e884fa73b52: metahelm: cloudkeeper-proxy: running helm install\n",

**Comment by mikeykhalil** [comment]
Good catch. This is particularly a bad issue because error notifications are not sent when the global timeout is reached. 

https://github.com/dollarshaveclub/acyl/issues/33

**Comment by bkeroackdsc** [comment]
It's not clear to me what this report is saying.

> given a namespace for a DQA was deleted - could have been manually or by ACYL
when an update to the PR associated with the namespace

I understand manual, out-of-band NS deletion (which may not be something we want to support, but ok), but I don't know what you mean by "when an update to the PR associated with the namespace". You're missing the end of that sentence perhaps?

> then ACYL will call metahelm to install charts into that namespace
and will not return an error but will timeout

For a manually deleted namespace, this behavior makes perfect sense as the database will still indicate that the namespace exists. We should probably add a sanity check prior to any kind of namespace operation to verify that it still exists, regardless of the state of the database.

**Comment by cleanshavenalex** [comment]
` We should probably add a sanity check prior to any kind of namespace operation to verify that it still exists, regardless of the state of the database.` 

`add a sanity check prior to any kind of namespace operation` >`check if namespace exists before calling metahelm`

**Comment by bkeroackdsc** [comment]
Not sure if still applicable.
