### ISSUE TITLE
Do not delete namespace if PR is still open

### ISSUE THREAD

**Issue by cleanshavenalex** [dollarshaveclub/acyl#42]
If the first attempt at building an environment for a PR fails, the namespace will be terminated

on subsequent updates to the PR , ACYL will try to install charts into a namespace that no longer exists

we should not delete namespaces associated with PR still open

**Comment by mikeykhalil** [comment]
So Acyl has a slightly different behavior, but still solves the root issue that this you are addressing. 

After https://github.com/dollarshaveclub/acyl/pull/37 was merged in, here is what Acyl will do. 

1. User opens a PR and that environment fails to spawn (e.g. bad code was pushed and a pod is in CrashLoopBackoff), the namespace will be terminated. 
2. The next time a user makes an update by amending a commit or pushing a new commit to that branch, it will create a new environment. 

So not the exact behavior you suggested, but I think it still solves the root issue of not having an environment spin up as expected. 

Going to close this issue but feel free to reopen if you want to discuss more.
